name: Deploy to IIS with Self-Hosted Runner Main

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Publish app
        run: dotnet publish -c Release -o ./publish

      - name: Stop, Deploy and Restart IIS site
        shell: pwsh
        run: |
          Import-Module WebAdministration
          Write-Host "Deteniendo sitio y App Pool de IIS..."
          Stop-Website -Name "proan" -ErrorAction SilentlyContinue
          Stop-WebAppPool -Name "proan" -ErrorAction SilentlyContinue

          Write-Host "Limpiando y copiando archivos a IIS..."
          Remove-Item "C:\inetpub\wwwroot\proan\*" -Recurse -Force -ErrorAction SilentlyContinue
          Copy-Item -Path ".\publish\*" -Destination "C:\inetpub\wwwroot\proan" -Recurse -Force

          Write-Host "Iniciando sitio y App Pool de IIS..."
          Start-WebAppPool -Name "proan"
          Start-Website -Name "proan"
