name: Deploy to IIS with Self-Hosted Runner

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Publish app
        run: dotnet publish -c Release -o ./publish

      - name: Deploy to IIS folder
        run: |
          Write-Host "Copiando archivos a IIS..."
          Copy-Item -Path ".\publish\*" -Destination "C:\inetpub\wwwroot\HolaMundoWeb" -Recurse -Force
