name: Deploy to IIS with Self-Hosted Runner

on:
  push:
    branches:
      - main   # Cambia si usas otra rama para producción

jobs:
  build-and-deploy:
    runs-on: self-hosted   # importante: apunta a tu runner en el servidor

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Publish app
        run: dotnet publish -c Release -o ./publish

      - name: Deploy to IIS folder
        run: |
          Write-Host "Copiando archivos a IIS..."
          Copy-Item -Path ".\publish\*" -Destination "C:\inetpub\wwwroot\HolaMundoWeb" -Recurse -Force
